# Server Configuration
server:
  port: 3000
  env: development

# Database Configuration
database:
  dialect: mariadb
  host: localhost
  port: 3306
  username: root
  password: ''
  database: network_monitor
  logging: true

# JWT Configuration
jwt:
  secret: your-secret-key
  expiresIn: 24h
